### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by Pyrolr** [two-tap/two-tap-ios-swift-example#2]
Current Swift example is not working properly it always gives 'Oops an error occurred'
If sample demo is given with sample public_token and unique_token and successful response it will be better to check the functionality before implementing in the app

**Comment by saul51292** [comment]
Hey,
Are you sure you’re also running TwoTap’s backend-example?
You can find it here

https://github.com/two-tap/two-tap-backend-example <https://github.com/two-tap/two-tap-backend-example>

It must be running for the sample app to work, otherwise, it will keep giving you that error

**Comment by Pyrolr** [comment]
No I am not running that backend as i didn't find that information in the swift readme file  , I will check that backend site 

Thanks for the prompt reply

**Comment by saul51292** [comment]
No problem! 
I've updated the readme file with the backend information.
