### ISSUE TITLE
Products Crash the App

### ISSUE THREAD

**Issue by nevinjethmalani** [two-tap/two-tap-ios-swift-example#3]
There are a few products that we have come across that will crash the app. Here are two that we noticed right away but we have come across others as well. 

https://www.jcrew.com/mens_category/polostees/shortsleevepolos/PRDOVR~93952/93952.jsp
https://www.toryburch.com/bombé-t-zip-continental-wallet/21169063.html?cgid=shops-wallet-guide&start=2&dwvar_21169063_color=261

**Comment by sradu** [comment]
Fixed.
